name: 'Setup Environment'
description: 'setup env with packages values'
author: 'dnettoRaw'
inputs:
  path:
    description: "package.json location"
    required: false
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
